name       : rtmidi
version    : 2.1.1
release    : 2
source     :
    - http://www.music.mcgill.ca/~gary/rtmidi/release/rtmidi-2.1.1.tar.gz : 1dd990705fbe003616af9207c5ea2ece2a6212388a41c8b2b2e191055181e286
license    : MIT
component  : multimedia.library
summary    : RtMidi is a set of C++ classes (RtMidiIn, RtMidiOut and API-specific
    classes) that provides a common API (Application Programming Interface) for realtime
    MIDI input/output across Linux (ALSA & JACK), Macintosh OS X (CoreMIDI & JACK),
    and Windows (Multimedia Library) operating systems.
description: |
    RtMidi is a set of C++ classes (RtMidiIn, RtMidiOut and API-specific classes) that provides a common API (Application Programming Interface) for realtime MIDI input/output across Linux (ALSA & JACK), Macintosh OS X (CoreMIDI & JACK), and Windows (Multimedia Library) operating systems. RtMidi significantly simplifies the process of interacting with computer MIDI hardware and software. It was designed with the following goals
builddeps  :
    - pkgconfig(alsa)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
