name       : rtmidi
version    : 2.1.1
release    : 6
source     :
    - https://github.com/thestk/rtmidi/archive/2.1.1.tar.gz : a015fbed67c777c7bc7bbcb96c07386ba3a8ff21006b411331e6f0b9f3f14d11
license    : MIT
component  : multimedia.library
summary    : RtMidi is a set of C++ classes (RtMidiIn, RtMidiOut and API-specific
    classes) that provides a common API (Application Programming Interface) for realtime
    MIDI input/output across Linux (ALSA & JACK), Macintosh OS X (CoreMIDI & JACK),
    and Windows (Multimedia Library) operating systems.
description: |
    RtMidi is a set of C++ classes (RtMidiIn, RtMidiOut and API-specific classes) that provides a common API (Application Programming Interface) for realtime MIDI input/output across Linux (ALSA & JACK), Macintosh OS X (CoreMIDI & JACK), and Windows (Multimedia Library) operating systems. RtMidi significantly simplifies the process of interacting with computer MIDI hardware and software. It was designed with the following goals
builddeps  :
    - pkgconfig(alsa)
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
